### PR TITLE
Fix .count invocation on has_many :through relations

### PR DESCRIPTION
**Pull request by vjt**

### CODE REVIEW

**Comment by vjt** [comment]
@pzac @lleirborras if it is good for you, it is good for me. The 4.2 issue triggered a good refactoring and performance improvement.

Once you deem this ready let me know and I merge and cut a new release.

Cheers

**Comment by lleirborras** [comment]
`return 'LGTM' if 'G' == 'Gay'`

**Comment by pzac** [comment]
🚢

**Comment by vjt** [comment]
Done, released as `v0.11.1`

**Pull request merged**
