### PR TITLE
Fix CodeClimate test coverage

### PR DESCRIPTION
**Pull request by tagliala**
OT: Why travis does not run tests on other branches different than master?

Answering myself:

image

Enabled

### CODE REVIEW

**Comment by vjt** [comment]
Is then
```ruby
  gem.add_development_dependency 'codeclimate-test-reporter'
```
this still required in `gemspec`?

**Comment by tagliala** [comment]
Good catch. I think it is not needed and it has also been deprecated

Ref: https://github.com/codeclimate/ruby-test-reporter

**Comment by tagliala** [comment]
Ok, we are affected by codeclimate/test-reporter#418

**Comment by tagliala** [comment]
I think this will work

**Comment by vjt** [comment]
🥇

**Pull request merged**
